Feature/hms 104 prevent to merge the pr with new
pleo-io/actions pull request #113
Opened 2022-05-18 15:55 UTC by pleorotus

2022-05-19 09:36 UTC, igorDolzh requested changes
Nice 1,3kk change!
I left some comments, please update!

2022-05-19 09:36 UTC, igorDolzh commented on find-unsubmitted-keys/src/main.ts
> +            if(!allLokaliseKeys.includes(encodeURIComponent(str.replace(/\\/g, '')))){
Why do you need `encodeURIComponent(str.replace(/\\/g, '')` for keys from github?

2022-05-19 09:36 UTC, igorDolzh commented on find-unsubmitted-keys/src/old_main.ts
> +import * as ghCore from "@actions/core"
Why do you need `old_main`?

2022-05-19 09:36 UTC, igorDolzh commented on find-unsubmitted-keys/README.md
> +# find-unsubmitted-keys
Incorrect or outdated README.md. Please correct

2022-05-19 09:43 UTC, igorDolzh commented
@pleorotus Also, Radu, give the PR a good title and description

2022-05-19 11:39 UTC, pleorotus commented on find-unsubmitted-keys/src/main.ts
> +        })
Why can't it be correct? I didn't see any issues with it, especially since the new array is only used for reading so refs are sufficient. I looked it up and can't find docs against this practice but if I'm missing some info, please share.
Changed it to a foreach loop

2022-05-19 11:43 UTC, pleorotus commented on find-unsubmitted-keys/src/main.ts
> +            if(!allLokaliseKeys.includes(encodeURIComponent(str.replace(/\\/g, '')))){
The comparison fails without it. Used a [jsFiddle](https://jsfiddle.net/eLgma6hj/63/) to try out various combinations and this was the 1st to work. I assume it's because whatever the string displayed is, it's not the actuall representation at the time of this assertion. Various chars are encoded in transition and since the strings come from different sources, I assume they go through different encoding steps. As per my investigation, this guarantees same encoding on all chars, regardless of past filters.

2022-05-19 11:46 UTC, pleorotus commented on find-unsubmitted-keys/src/main.ts
> +        })
done

2022-05-19 11:54 UTC, pleorotus commented on find-unsubmitted-keys/src/old_main.ts
> +import * as ghCore from "@actions/core"
It's not needed; kept it for reference and removed it now.

2022-05-19 12:07 UTC, igorDolzh commented on find-unsubmitted-keys/src/main.ts
> +        })
`map` is for updating the array and returning a new one
`forEach` is for looping the items of the array without the returning

If you use `map`, but do not return anything, you make a mistake and should use `forEach` instead
In your particular case, no need to create an empty array and push items one by one into it, it feels redundant and overkill, because if you want to update each item inside the array, it is`map` function specially created for this purpose.

you could further update the code to look it like

```
const localiseKeys =  await lokalise.keys.list({
            project_id: lokaliseProjectId,
            limit: 5000,
        })
.then((result) => {
  return result.items.map((item) => encodeURIComponent(item.key_name.web.replace(/\\/g, '')))
})
```

or create a dedicated function for that
```
async function getLocaliseKeys() {

const localiseKeys =  await lokalise.keys.list({
            project_id: lokaliseProjectId,
            limit: 5000,
        })
return localiseKeys.items.map((item) => encodeURIComponent(item.key_name.web.replace(/\\/g, '')))
}
```

both variants are better than `forEach`

2022-05-19 12:14 UTC, igorDolzh commented on find-unsubmitted-keys/src/main.ts
> +            if(!allLokaliseKeys.includes(encodeURIComponent(str.replace(/\\/g, '')))){
I think we should enlist the possible incoming strings both from localise and git and see where you get this redundant "\\".  Could you enlist cases where such thing is necessary?

2022-05-20 19:05 UTC, igorDolzh approved these changes
Overall good, thank you for addressing my comments!

2022-05-23 13:54 UTC, merged